service: aws-node
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: us-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
      - dynamodb:*
      Resource: 
      - arn:aws:dynamodb:us-west-1:548577335620:table/TodoTable

functions:
  addTodo:
    handler: src/addTodo.handler
    events:
      - http:
          path: /
          method: post

resources:
  Resources: 
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TodoTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
